import Head from 'next/head'
import { useState } from 'react'
import { useSession, signIn, signOut } from "next-auth/react"
import { FaGoogle } from 'react-icons/fa'
import { db } from '@/firebase.config'
import { collection, addDoc, serverTimestamp } from "firebase/firestore"

export default function Home() {
  const [loading, setLoading] = useState(false)
  const { data: session } = useSession()

  const handleSignIn = async () => {
    setLoading(true)

    try {
      await signIn('google')

      await addDoc(collection(db, 'users'), {
        name: session?.user?.name,
        email: session?.user?.email,
        image: session?.user?.image,
        createdAt: serverTimestamp()
      })
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <>
      <Head>
        <title>TodoList Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!session ? (
          <>
            <h3 className='text-2xl font-semibold mb-3'>
              You are not signed in
            </h3>
            <button
              className='bg-slate-500 px-4 py-2 rounded-md flex items-center gap-3'
              // onClick={() => signIn('google')}
              onClick={handleSignIn}
            >
              {!loading ? (
                <>
                  <span className='text-white'>
                    Sign In with Google
                  </span>
                  <FaGoogle className='text-white' />
                </>
              ) : (
                <span className='text-black'>
                  Loading...
                </span>
              )}
            </button>
          </>
        ) : (
          <>
            <h3 className='text-2xl font-semibold mb-6'>
              Hello {session.user.name}!
            </h3>
            <button
              className='bg-red-500 text-white px-4 py-2 rounded-md'
              onClick={() => signOut()}
            >
              Sign Out
            </button>
          </>
        )}
      </main>
    </>
  )
}
